---
- name: Add repos for Ubuntu
  block:
    - name: Install software-properties-common.
      apt:
        state: present
        name: software-properties-common
        cache_valid_time: 3600

    - name: Add repos
      apt_repository:
        repo: "{{certbot_eff_repo}}"
        update_cache: yes

  when: ansible_distribution == "Ubuntu"
