---
- name: Install Certbot.
  package: "name={{ certbot_package }} state={{ 'latest' if certbot_update_when_installed else 'present'}}"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
